COMPRESSED_DIGITAL_AUDIO_PROTECTION = (100, 301)

LEVEL_100 = COMPRESSED_DIGITAL_AUDIO_PROTECTION[0]  # 'LEVEL_100
LEVEL_301 = COMPRESSED_DIGITAL_AUDIO_PROTECTION[1]  # 'LEVEL_301'

def check(compressed_digital_audio) -> bool:
    return compressed_digital_audio in COMPRESSED_DIGITAL_AUDIO_PROTECTION
