UNCOMPRESSED_DIGITAL_AUDIO_PROTECTION = (100, 250, 300, 301)

LEVEL_100 = UNCOMPRESSED_DIGITAL_AUDIO_PROTECTION[0]  # 'LEVEL_100'
LEVEL_250 = UNCOMPRESSED_DIGITAL_AUDIO_PROTECTION[1]  # 'LEVEL_250'
LEVEL_300 = UNCOMPRESSED_DIGITAL_AUDIO_PROTECTION[2]  # 'LEVEL_300'
LEVEL_301 = UNCOMPRESSED_DIGITAL_AUDIO_PROTECTION[3]  # 'LEVEL_301',

def check(uncompressed_digital_audio) -> bool:
    return uncompressed_digital_audio in UNCOMPRESSED_DIGITAL_AUDIO_PROTECTION
